const fs = require('fs');
const path = require('path');

const apiKey = process.env.GOOGLE_MAPS_API_KEY || '';
const mapId = process.env.GOOGLE_MAPS_MAP_ID || '';

if (!apiKey) {
  console.warn('WARNING: GOOGLE_MAPS_API_KEY is not set. The app will not load Google Maps.');
}

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });

const devContent = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: false,
  googleMapsApiKey: '${apiKey}',
  mapId: '${mapId}',
};
`;

const prodContent = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  googleMapsApiKey: '${apiKey}',
  mapId: '${mapId}',
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), devContent);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), prodContent);

console.log('Environment files generated successfully.');
